export default function index() {
  return (
    <g
      data-component="svg__block"
      data-section-name="CENTER"
      data-section-id="s_26"
      class="section"
      transform=""
    >
      <g data-component="svg__row" data-row-name="A" class="row">
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORTHE"
          class="seat"
          data-seat-name="39"
          cx="5670.8"
          cy="4332.32"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORTHA"
          class="seat"
          data-seat-name="38"
          cx="5614.45"
          cy="4315.22"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORTG4"
          class="seat"
          data-seat-name="37"
          cx="5557.23"
          cy="4301.25"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORTGY"
          class="seat"
          data-seat-name="36"
          cx="5499.98"
          cy="4287.27"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORTGU"
          class="seat"
          data-seat-name="35"
          cx="5442.02"
          cy="4276.94"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORTGQ"
          class="seat"
          data-seat-name="34"
          cx="5383.88"
          cy="4267.6"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORTGM"
          class="seat"
          data-seat-name="33"
          cx="5325.56"
          cy="4259.51"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORTGI"
          class="seat"
          data-seat-name="32"
          cx="5266.83"
          cy="4254.82"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORTGE"
          class="seat"
          data-seat-name="31"
          cx="5208.14"
          cy="4250.14"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORTGA"
          class="seat"
          data-seat-name="30"
          cx="5149.24"
          cy="4249"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORSHE"
          class="seat"
          data-seat-name="29"
          cx="5090.25"
          cy="4249"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORSHA"
          class="seat"
          data-seat-name="28"
          cx="5031.35"
          cy="4250.17"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORSG4"
          class="seat"
          data-seat-name="27"
          cx="4972.64"
          cy="4254.86"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORSGY"
          class="seat"
          data-seat-name="26"
          cx="4913.97"
          cy="4259.54"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORSGU"
          class="seat"
          data-seat-name="25"
          cx="4855.65"
          cy="4267.66"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORSGQ"
          class="seat"
          data-seat-name="24"
          cx="4797.47"
          cy="4277.01"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORSGM"
          class="seat"
          data-seat-name="23"
          cx="4739.49"
          cy="4287.38"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORSGI"
          class="seat"
          data-seat-name="22"
          cx="4682.25"
          cy="4301.36"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORSGE"
          class="seat"
          data-seat-name="21"
          cx="4624.99"
          cy="4315.34"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ECORSGA"
          class="seat"
          data-seat-name="20"
          cx="4568.65"
          cy="4332.48"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="B" class="row">
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORUGE"
          class="seat"
          data-seat-name="41"
          cx="5702.82"
          cy="4239.7"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORUGA"
          class="seat"
          data-seat-name="40"
          cx="5646.3"
          cy="4222.12"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORTHE"
          class="seat"
          data-seat-name="39"
          cx="5588.75"
          cy="4208.07"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORTHA"
          class="seat"
          data-seat-name="38"
          cx="5531.24"
          cy="4194.02"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORTG4"
          class="seat is-available is-filtered"
          data-seat-name="37"
          cx="5473.15"
          cy="4182.69"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORTGY"
          class="seat"
          data-seat-name="36"
          cx="5414.68"
          cy="4173.29"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORTGU"
          class="seat"
          data-seat-name="35"
          cx="5356.21"
          cy="4163.89"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORTGQ"
          class="seat"
          data-seat-name="34"
          cx="5297.19"
          cy="4158.93"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORTGM"
          class="seat"
          data-seat-name="33"
          cx="5238.18"
          cy="4154.22"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORTGI"
          class="seat"
          data-seat-name="32"
          cx="5179.11"
          cy="4151"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORTGE"
          class="seat"
          data-seat-name="31"
          cx="5119.9"
          cy="4151"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORTGA"
          class="seat"
          data-seat-name="30"
          cx="5060.69"
          cy="4151"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORSHE"
          class="seat"
          data-seat-name="29"
          cx="5001.62"
          cy="4154.23"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORSHA"
          class="seat"
          data-seat-name="28"
          cx="4942.62"
          cy="4158.94"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORSG4"
          class="seat"
          data-seat-name="27"
          cx="4883.67"
          cy="4163.89"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORSGY"
          class="seat"
          data-seat-name="26"
          cx="4825.15"
          cy="4173.3"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORSGU"
          class="seat"
          data-seat-name="25"
          cx="4766.64"
          cy="4182.71"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORSGQ"
          class="seat"
          data-seat-name="24"
          cx="4708.56"
          cy="4194.05"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORSGM"
          class="seat"
          data-seat-name="23"
          cx="4651.06"
          cy="4208.09"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORSGI"
          class="seat"
          data-seat-name="22"
          cx="4593.56"
          cy="4222.13"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EEORSGE"
          class="seat"
          data-seat-name="21"
          cx="4537.05"
          cy="4239.71"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="C" class="row">
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORUGQ"
          class="seat"
          data-seat-name="44"
          cx="5734.85"
          cy="4147.07"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORUGM"
          class="seat"
          data-seat-name="43"
          cx="5678.15"
          cy="4129.02"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORUGI"
          class="seat"
          data-seat-name="42"
          cx="5620.33"
          cy="4114.9"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORUGE"
          class="seat"
          data-seat-name="41"
          cx="5562.52"
          cy="4100.78"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORUGA"
          class="seat"
          data-seat-name="40"
          cx="5504.34"
          cy="4088.44"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORTHE"
          class="seat"
          data-seat-name="39"
          cx="5445.59"
          cy="4079"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORTHA"
          class="seat"
          data-seat-name="38"
          cx="5386.82"
          cy="4069.55"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORTG4"
          class="seat"
          data-seat-name="37"
          cx="5327.69"
          cy="4063.05"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORTGY"
          class="seat"
          data-seat-name="36"
          cx="5268.36"
          cy="4058.32"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORTGU"
          class="seat"
          data-seat-name="35"
          cx="5209.07"
          cy="4053.59"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORTGQ"
          class="seat"
          data-seat-name="34"
          cx="5149.63"
          cy="4053"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORTGM"
          class="seat"
          data-seat-name="33"
          cx="5090.19"
          cy="4053"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORTGI"
          class="seat"
          data-seat-name="32"
          cx="5030.77"
          cy="4053.59"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORTGE"
          class="seat"
          data-seat-name="31"
          cx="4971.47"
          cy="4058.33"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORTGA"
          class="seat"
          data-seat-name="30"
          cx="4912.18"
          cy="4063.06"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORSHE"
          class="seat"
          data-seat-name="29"
          cx="4853.06"
          cy="4069.56"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORSHA"
          class="seat"
          data-seat-name="28"
          cx="4794.24"
          cy="4079.01"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORSG4"
          class="seat"
          data-seat-name="27"
          cx="4735.42"
          cy="4088.47"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORSGY"
          class="seat"
          data-seat-name="26"
          cx="4677.22"
          cy="4100.83"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORSGU"
          class="seat"
          data-seat-name="25"
          cx="4619.41"
          cy="4114.94"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORSGQ"
          class="seat"
          data-seat-name="24"
          cx="4561.59"
          cy="4129.06"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EGORSGM"
          class="seat"
          data-seat-name="23"
          cx="4504.92"
          cy="4147.12"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="D" class="row">
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORUGY"
          class="seat"
          data-seat-name="46"
          cx="5766.88"
          cy="4054.44"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORUGU"
          class="seat"
          data-seat-name="45"
          cx="5710.05"
          cy="4035.93"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORUGQ"
          class="seat"
          data-seat-name="44"
          cx="5651.97"
          cy="4021.75"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORUGM"
          class="seat"
          data-seat-name="43"
          cx="5593.92"
          cy="4007.57"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORUGI"
          class="seat"
          data-seat-name="42"
          cx="5535.67"
          cy="3994.22"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORUGE"
          class="seat"
          data-seat-name="41"
          cx="5476.66"
          cy="3984.74"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORUGA"
          class="seat"
          data-seat-name="40"
          cx="5417.63"
          cy="3975.25"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORTHE"
          class="seat"
          data-seat-name="39"
          cx="5358.42"
          cy="3967.19"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORTHA"
          class="seat"
          data-seat-name="38"
          cx="5298.82"
          cy="3962.44"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORTG4"
          class="seat"
          data-seat-name="37"
          cx="5239.23"
          cy="3957.68"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORTGY"
          class="seat"
          data-seat-name="36"
          cx="5179.58"
          cy="3955"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORTGU"
          class="seat"
          data-seat-name="35"
          cx="5119.85"
          cy="3955"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORTGQ"
          class="seat"
          data-seat-name="34"
          cx="5060.13"
          cy="3955"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORTGM"
          class="seat"
          data-seat-name="33"
          cx="5000.48"
          cy="3957.7"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORTGI"
          class="seat"
          data-seat-name="32"
          cx="4940.9"
          cy="3962.45"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORTGE"
          class="seat"
          data-seat-name="31"
          cx="4881.31"
          cy="3967.21"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORTGA"
          class="seat"
          data-seat-name="30"
          cx="4822.07"
          cy="3975.28"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORSHE"
          class="seat"
          data-seat-name="29"
          cx="4762.99"
          cy="3984.78"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORSHA"
          class="seat"
          data-seat-name="28"
          cx="4703.92"
          cy="3994.28"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORSG4"
          class="seat"
          data-seat-name="27"
          cx="4645.63"
          cy="4007.66"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORSGY"
          class="seat"
          data-seat-name="26"
          cx="4587.51"
          cy="4021.85"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORSGU"
          class="seat"
          data-seat-name="25"
          cx="4529.38"
          cy="4036.05"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EIORSGQ"
          class="seat"
          data-seat-name="24"
          cx="4472.54"
          cy="4054.61"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="E" class="row">
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORUHA"
          class="seat"
          data-seat-name="48"
          cx="5798.92"
          cy="3961.82"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORUG4"
          class="seat"
          data-seat-name="47"
          cx="5741.94"
          cy="3942.94"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORUGY"
          class="seat"
          data-seat-name="46"
          cx="5683.65"
          cy="3928.6"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORUGU"
          class="seat"
          data-seat-name="45"
          cx="5625.34"
          cy="3914.36"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORUGQ"
          class="seat"
          data-seat-name="44"
          cx="5567.03"
          cy="3900.13"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORUGM"
          class="seat"
          data-seat-name="43"
          cx="5507.77"
          cy="3890.48"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORUGI"
          class="seat is-available is-filtered"
          data-seat-name="42"
          cx="5448.52"
          cy="3880.96"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORUGE"
          class="seat"
          data-seat-name="41"
          cx="5389.28"
          cy="3871.43"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORUGA"
          class="seat"
          data-seat-name="40"
          cx="5329.49"
          cy="3866.57"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORTHE"
          class="seat"
          data-seat-name="39"
          cx="5269.66"
          cy="3861.8"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORTHA"
          class="seat"
          data-seat-name="38"
          cx="5209.82"
          cy="3857.03"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORTG4"
          class="seat"
          data-seat-name="37"
          cx="5149.82"
          cy="3857"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORTGY"
          class="seat"
          data-seat-name="36"
          cx="5089.84"
          cy="3857"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORTGU"
          class="seat"
          data-seat-name="35"
          cx="5029.84"
          cy="3857.05"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORTGQ"
          class="seat"
          data-seat-name="34"
          cx="4970"
          cy="3861.82"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORTGM"
          class="seat"
          data-seat-name="33"
          cx="4910.14"
          cy="3866.6"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORTGI"
          class="seat"
          data-seat-name="32"
          cx="4850.31"
          cy="3871.48"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORTGE"
          class="seat"
          data-seat-name="31"
          cx="4791.07"
          cy="3881.01"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORTGA"
          class="seat"
          data-seat-name="30"
          cx="4731.84"
          cy="3890.53"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORSHE"
          class="seat"
          data-seat-name="29"
          cx="4672.67"
          cy="3900.18"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORSHA"
          class="seat"
          data-seat-name="28"
          cx="4614.39"
          cy="3914.41"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORSG4"
          class="seat"
          data-seat-name="27"
          cx="4556.1"
          cy="3928.64"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORSGY"
          class="seat"
          data-seat-name="26"
          cx="4497.87"
          cy="3942.97"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EKORSGU"
          class="seat"
          data-seat-name="25"
          cx="4440.9"
          cy="3961.85"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="F" class="row">
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORVGE"
          class="seat"
          data-seat-name="51"
          cx="5830.94"
          cy="3869.19"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORVGA"
          class="seat"
          data-seat-name="50"
          cx="5776.05"
          cy="3851"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORUHE"
          class="seat"
          data-seat-name="49"
          cx="5720.05"
          cy="3836.61"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORUHA"
          class="seat"
          data-seat-name="48"
          cx="5663.85"
          cy="3822.89"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORUG4"
          class="seat"
          data-seat-name="47"
          cx="5607.64"
          cy="3809.16"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORUGY"
          class="seat"
          data-seat-name="46"
          cx="5550.91"
          cy="3798.16"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORUGU"
          class="seat"
          data-seat-name="45"
          cx="5493.82"
          cy="3788.98"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORUGQ"
          class="seat"
          data-seat-name="44"
          cx="5436.71"
          cy="3779.8"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORUGM"
          class="seat"
          data-seat-name="43"
          cx="5379.41"
          cy="3772.25"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORUGI"
          class="seat"
          data-seat-name="42"
          cx="5321.79"
          cy="3767.65"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORUGE"
          class="seat"
          data-seat-name="41"
          cx="5264.11"
          cy="3763.05"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORUGA"
          class="seat"
          data-seat-name="40"
          cx="5206.42"
          cy="3759"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORTHE"
          class="seat"
          data-seat-name="39"
          cx="5148.61"
          cy="3759"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORTHA"
          class="seat"
          data-seat-name="38"
          cx="5090.78"
          cy="3759"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORTG4"
          class="seat"
          data-seat-name="37"
          cx="5032.95"
          cy="3759"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORTGY"
          class="seat is-available is-filtered"
          data-seat-name="36"
          cx="4975.24"
          cy="3763.09"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORTGU"
          class="seat"
          data-seat-name="35"
          cx="4917.57"
          cy="3767.69"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORTGQ"
          class="seat"
          data-seat-name="34"
          cx="4859.89"
          cy="3772.29"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORTGM"
          class="seat"
          data-seat-name="33"
          cx="4802.57"
          cy="3779.9"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORTGI"
          class="seat"
          data-seat-name="32"
          cx="4745.46"
          cy="3789.08"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORTGE"
          class="seat"
          data-seat-name="31"
          cx="4688.37"
          cy="3798.26"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORTGA"
          class="seat"
          data-seat-name="30"
          cx="4631.66"
          cy="3809.31"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORSHE"
          class="seat"
          data-seat-name="29"
          cx="4575.45"
          cy="3823.04"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORSHA"
          class="seat"
          data-seat-name="28"
          cx="4519.23"
          cy="3836.77"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORSG4"
          class="seat"
          data-seat-name="27"
          cx="4463.22"
          cy="3851.21"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EMORSGY"
          class="seat"
          data-seat-name="26"
          cx="4408.31"
          cy="3869.41"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="G" class="row">
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORVGM"
          class="seat"
          data-seat-name="53"
          cx="5862.97"
          cy="3776.56"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORVGI"
          class="seat"
          data-seat-name="52"
          cx="5807.81"
          cy="3758.28"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORVGE"
          class="seat"
          data-seat-name="51"
          cx="5751.63"
          cy="3743.44"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORVGA"
          class="seat"
          data-seat-name="50"
          cx="5695.15"
          cy="3729.65"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORUHE"
          class="seat"
          data-seat-name="49"
          cx="5638.68"
          cy="3715.86"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORUHA"
          class="seat"
          data-seat-name="48"
          cx="5581.84"
          cy="3703.87"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORUG4"
          class="seat"
          data-seat-name="47"
          cx="5524.42"
          cy="3694.64"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORUGY"
          class="seat"
          data-seat-name="46"
          cx="5466.99"
          cy="3685.41"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORUGU"
          class="seat"
          data-seat-name="45"
          cx="5409.55"
          cy="3676.34"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORUGQ"
          class="seat"
          data-seat-name="44"
          cx="5351.63"
          cy="3671.72"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORUGM"
          class="seat"
          data-seat-name="43"
          cx="5293.7"
          cy="3667.1"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORUGI"
          class="seat"
          data-seat-name="42"
          cx="5235.73"
          cy="3662.47"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORUGE"
          class="seat"
          data-seat-name="41"
          cx="5177.66"
          cy="3661"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORUGA"
          class="seat"
          data-seat-name="40"
          cx="5119.52"
          cy="3661"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORTHE"
          class="seat"
          data-seat-name="39"
          cx="5061.4"
          cy="3661"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORTHA"
          class="seat"
          data-seat-name="38"
          cx="5003.3"
          cy="3662.54"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORTG4"
          class="seat"
          data-seat-name="37"
          cx="4945.32"
          cy="3667.17"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORTGY"
          class="seat"
          data-seat-name="36"
          cx="4887.32"
          cy="3671.79"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORTGU"
          class="seat"
          data-seat-name="35"
          cx="4829.35"
          cy="3676.42"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORTGQ"
          class="seat"
          data-seat-name="34"
          cx="4771.91"
          cy="3685.57"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORTGM"
          class="seat"
          data-seat-name="33"
          cx="4714.49"
          cy="3694.8"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORTGI"
          class="seat"
          data-seat-name="32"
          cx="4657.11"
          cy="3704.03"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORTGE"
          class="seat"
          data-seat-name="31"
          cx="4600.34"
          cy="3716.08"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORTGA"
          class="seat"
          data-seat-name="30"
          cx="4543.93"
          cy="3729.86"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORSHE"
          class="seat"
          data-seat-name="29"
          cx="4487.51"
          cy="3743.63"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORSHA"
          class="seat"
          data-seat-name="28"
          cx="4431.42"
          cy="3758.51"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EOORSG4"
          class="seat"
          data-seat-name="27"
          cx="4376.28"
          cy="3776.78"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="H" class="row">
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORVGQ"
          class="seat"
          data-seat-name="54"
          cx="5895"
          cy="3683.94"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORVGM"
          class="seat"
          data-seat-name="53"
          cx="5837.45"
          cy="3664.86"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORVGI"
          class="seat"
          data-seat-name="52"
          cx="5778.9"
          cy="3649.22"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORVGE"
          class="seat"
          data-seat-name="51"
          cx="5719.99"
          cy="3634.84"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORVGA"
          class="seat"
          data-seat-name="50"
          cx="5661.09"
          cy="3620.46"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORUHE"
          class="seat"
          data-seat-name="49"
          cx="5601.83"
          cy="3607.83"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORUHA"
          class="seat"
          data-seat-name="48"
          cx="5541.99"
          cy="3598.21"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORUG4"
          class="seat"
          data-seat-name="47"
          cx="5482.15"
          cy="3588.59"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORUGY"
          class="seat"
          data-seat-name="46"
          cx="5422.3"
          cy="3579.04"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORUGU"
          class="seat"
          data-seat-name="45"
          cx="5361.89"
          cy="3574.22"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORUGQ"
          class="seat"
          data-seat-name="44"
          cx="5301.43"
          cy="3569.4"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORUGM"
          class="seat"
          data-seat-name="43"
          cx="5240.98"
          cy="3564.58"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORUGI"
          class="seat"
          data-seat-name="42"
          cx="5180.39"
          cy="3563"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORUGE"
          class="seat"
          data-seat-name="41"
          cx="5119.72"
          cy="3563"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORUGA"
          class="seat"
          data-seat-name="40"
          cx="5059.07"
          cy="3563"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORTHE"
          class="seat"
          data-seat-name="39"
          cx="4998.44"
          cy="3564.62"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORTHA"
          class="seat"
          data-seat-name="38"
          cx="4937.93"
          cy="3569.44"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORTG4"
          class="seat"
          data-seat-name="37"
          cx="4877.42"
          cy="3574.27"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORTGY"
          class="seat"
          data-seat-name="36"
          cx="4816.95"
          cy="3579.1"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORTGU"
          class="seat"
          data-seat-name="35"
          cx="4757.13"
          cy="3588.69"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORTGQ"
          class="seat"
          data-seat-name="34"
          cx="4697.3"
          cy="3598.31"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORTGM"
          class="seat is-available is-filtered"
          data-seat-name="33"
          cx="4637.42"
          cy="3607.93"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORTGI"
          class="seat"
          data-seat-name="32"
          cx="4578.16"
          cy="3620.62"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORTGE"
          class="seat"
          data-seat-name="31"
          cx="4519.25"
          cy="3635"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORTGA"
          class="seat"
          data-seat-name="30"
          cx="4460.34"
          cy="3649.39"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORSHE"
          class="seat"
          data-seat-name="29"
          cx="4401.79"
          cy="3665.09"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EQORSHA"
          class="seat"
          data-seat-name="28"
          cx="4344.22"
          cy="3684.16"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="I" class="row">
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORVG4"
          class="seat"
          data-seat-name="57"
          cx="5927.03"
          cy="3591.31"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORVGY"
          class="seat"
          data-seat-name="56"
          cx="5871.38"
          cy="3572.87"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORVGU"
          class="seat"
          data-seat-name="55"
          cx="5814.94"
          cy="3557.14"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORVGQ"
          class="seat"
          data-seat-name="54"
          cx="5757.99"
          cy="3543.24"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORVGM"
          class="seat is-available is-filtered"
          data-seat-name="53"
          cx="5701.04"
          cy="3529.33"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORVGI"
          class="seat is-available is-filtered"
          data-seat-name="52"
          cx="5644.08"
          cy="3515.42"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORVGE"
          class="seat is-available is-filtered"
          data-seat-name="51"
          cx="5586.23"
          cy="3506.06"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORVGA"
          class="seat is-available is-filtered"
          data-seat-name="50"
          cx="5528.36"
          cy="3496.76"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORUHE"
          class="seat"
          data-seat-name="49"
          cx="5470.45"
          cy="3487.45"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORUHA"
          class="seat"
          data-seat-name="48"
          cx="5412.33"
          cy="3479.94"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORUG4"
          class="seat"
          data-seat-name="47"
          cx="5353.89"
          cy="3475.27"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORUGY"
          class="seat"
          data-seat-name="46"
          cx="5295.43"
          cy="3470.61"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORUGU"
          class="seat"
          data-seat-name="45"
          cx="5236.98"
          cy="3465.95"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORUGQ"
          class="seat"
          data-seat-name="44"
          cx="5178.36"
          cy="3465"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORUGM"
          class="seat"
          data-seat-name="43"
          cx="5119.67"
          cy="3465"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORUGI"
          class="seat"
          data-seat-name="42"
          cx="5061"
          cy="3465"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORUGE"
          class="seat"
          data-seat-name="41"
          cx="5002.34"
          cy="3465.99"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORUGA"
          class="seat"
          data-seat-name="40"
          cx="4943.81"
          cy="3470.66"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORTHE"
          class="seat"
          data-seat-name="39"
          cx="4885.28"
          cy="3475.33"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORTHA"
          class="seat"
          data-seat-name="38"
          cx="4826.81"
          cy="3480"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORTG4"
          class="seat"
          data-seat-name="37"
          cx="4768.69"
          cy="3487.57"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORTGY"
          class="seat"
          data-seat-name="36"
          cx="4710.82"
          cy="3496.87"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORTGU"
          class="seat"
          data-seat-name="35"
          cx="4652.9"
          cy="3506.19"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORTGQ"
          class="seat is-available is-filtered"
          data-seat-name="34"
          cx="4594.97"
          cy="3515.63"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORTGM"
          class="seat"
          data-seat-name="33"
          cx="4537.97"
          cy="3529.55"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORTGI"
          class="seat"
          data-seat-name="32"
          cx="4480.95"
          cy="3543.48"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORTGE"
          class="seat"
          data-seat-name="31"
          cx="4423.93"
          cy="3557.4"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORTGA"
          class="seat"
          data-seat-name="30"
          cx="4367.49"
          cy="3573.21"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5ESORSHE"
          class="seat"
          data-seat-name="29"
          cx="4311.87"
          cy="3591.64"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="J" class="row">
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORWGA"
          class="seat"
          data-seat-name="60"
          cx="5959.07"
          cy="3498.69"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORVHE"
          class="seat"
          data-seat-name="59"
          cx="5903.18"
          cy="3480.16"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORVHA"
          class="seat"
          data-seat-name="58"
          cx="5846.63"
          cy="3464"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORVG4"
          class="seat"
          data-seat-name="57"
          cx="5789.44"
          cy="3450.04"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORVGY"
          class="seat"
          data-seat-name="56"
          cx="5732.28"
          cy="3436.08"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORVGU"
          class="seat"
          data-seat-name="55"
          cx="5675.11"
          cy="3422.12"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORVGQ"
          class="seat is-available is-filtered"
          data-seat-name="54"
          cx="5617.18"
          cy="3411.78"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORVGM"
          class="seat is-available is-filtered"
          data-seat-name="53"
          cx="5559.06"
          cy="3402.43"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORVGI"
          class="seat is-available is-filtered"
          data-seat-name="52"
          cx="5500.95"
          cy="3393.09"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORVGE"
          class="seat is-available is-filtered"
          data-seat-name="51"
          cx="5442.79"
          cy="3384.06"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORVGA"
          class="seat"
          data-seat-name="50"
          cx="5384.11"
          cy="3379.37"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORUHE"
          class="seat"
          data-seat-name="49"
          cx="5325.43"
          cy="3374.69"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORUHA"
          class="seat"
          data-seat-name="48"
          cx="5266.76"
          cy="3370.01"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORUG4"
          class="seat"
          data-seat-name="47"
          cx="5207.99"
          cy="3367"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORUGY"
          class="seat"
          data-seat-name="46"
          cx="5149.07"
          cy="3367"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORUGU"
          class="seat"
          data-seat-name="45"
          cx="5090.13"
          cy="3367"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORUGQ"
          class="seat"
          data-seat-name="44"
          cx="5031.21"
          cy="3367"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORUGM"
          class="seat"
          data-seat-name="43"
          cx="4972.4"
          cy="3370.07"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORUGI"
          class="seat"
          data-seat-name="42"
          cx="4913.68"
          cy="3374.76"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORUGE"
          class="seat"
          data-seat-name="41"
          cx="4854.94"
          cy="3379.44"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORUGA"
          class="seat"
          data-seat-name="40"
          cx="4796.24"
          cy="3384.13"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORTHE"
          class="seat"
          data-seat-name="39"
          cx="4738.11"
          cy="3393.23"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORTHA"
          class="seat"
          data-seat-name="38"
          cx="4680"
          cy="3402.57"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORTG4"
          class="seat is-available is-filtered"
          data-seat-name="37"
          cx="4621.89"
          cy="3411.91"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORTGY"
          class="seat is-available is-filtered"
          data-seat-name="36"
          cx="4563.99"
          cy="3422.32"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORTGU"
          class="seat is-available is-filtered"
          data-seat-name="35"
          cx="4506.84"
          cy="3436.28"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORTGQ"
          class="seat"
          data-seat-name="34"
          cx="4449.68"
          cy="3450.23"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORTGM"
          class="seat"
          data-seat-name="33"
          cx="4392.5"
          cy="3464.19"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORTGI"
          class="seat"
          data-seat-name="32"
          cx="4335.94"
          cy="3480.43"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EUORTGE"
          class="seat"
          data-seat-name="31"
          cx="4280.06"
          cy="3498.95"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="K" class="row">
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORWGI"
          class="seat"
          data-seat-name="62"
          cx="5991.09"
          cy="3406.06"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORWGE"
          class="seat"
          data-seat-name="61"
          cx="5935.01"
          cy="3387.47"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORWGA"
          class="seat"
          data-seat-name="60"
          cx="5878.35"
          cy="3370.87"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORVHE"
          class="seat"
          data-seat-name="59"
          cx="5820.96"
          cy="3356.86"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORVHA"
          class="seat is-available is-filtered"
          data-seat-name="58"
          cx="5763.55"
          cy="3342.84"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORVG4"
          class="seat is-available is-filtered"
          data-seat-name="57"
          cx="5706.14"
          cy="3328.82"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORVGY"
          class="seat is-available is-filtered"
          data-seat-name="56"
          cx="5648.19"
          cy="3317.5"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORVGU"
          class="seat is-available is-filtered"
          data-seat-name="55"
          cx="5589.82"
          cy="3308.12"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORVGQ"
          class="seat is-available is-filtered"
          data-seat-name="54"
          cx="5531.47"
          cy="3298.74"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORVGM"
          class="seat is-available is-filtered"
          data-seat-name="53"
          cx="5473.13"
          cy="3289.36"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORVGI"
          class="seat is-available is-filtered"
          data-seat-name="52"
          cx="5414.39"
          cy="3283.48"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORVGE"
          class="seat is-available is-filtered"
          data-seat-name="51"
          cx="5355.49"
          cy="3278.78"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORVGA"
          class="seat is-available is-filtered"
          data-seat-name="50"
          cx="5296.6"
          cy="3274.08"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORUHE"
          class="seat is-available is-filtered"
          data-seat-name="49"
          cx="5237.68"
          cy="3269.38"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORUHA"
          class="seat"
          data-seat-name="48"
          cx="5178.56"
          cy="3269"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORUG4"
          class="seat"
          data-seat-name="47"
          cx="5119.41"
          cy="3269"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORUGY"
          class="seat is-available is-filtered"
          data-seat-name="46"
          cx="5060.23"
          cy="3269"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORUGU"
          class="seat is-available is-filtered"
          data-seat-name="45"
          cx="5001.11"
          cy="3269.47"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORUGQ"
          class="seat"
          data-seat-name="44"
          cx="4942.2"
          cy="3274.17"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORUGM"
          class="seat"
          data-seat-name="43"
          cx="4883.26"
          cy="3278.87"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORUGI"
          class="seat is-available is-filtered"
          data-seat-name="42"
          cx="4824.35"
          cy="3283.57"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORUGE"
          class="seat is-available is-filtered"
          data-seat-name="41"
          cx="4765.59"
          cy="3289.55"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORUGA"
          class="seat is-available is-filtered"
          data-seat-name="40"
          cx="4707.25"
          cy="3298.93"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORTHE"
          class="seat"
          data-seat-name="39"
          cx="4648.96"
          cy="3308.3"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORTHA"
          class="seat"
          data-seat-name="38"
          cx="4590.68"
          cy="3317.67"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORTG4"
          class="seat is-available is-filtered"
          data-seat-name="37"
          cx="4532.75"
          cy="3329.07"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORTGY"
          class="seat is-available is-filtered"
          data-seat-name="36"
          cx="4475.32"
          cy="3343.09"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORTGU"
          class="seat is-available is-filtered"
          data-seat-name="35"
          cx="4417.93"
          cy="3357.11"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORTGQ"
          class="seat is-available is-filtered"
          data-seat-name="34"
          cx="4360.55"
          cy="3371.12"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORTGM"
          class="seat"
          data-seat-name="33"
          cx="4303.92"
          cy="3387.8"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EWORTGI"
          class="seat"
          data-seat-name="32"
          cx="4247.83"
          cy="3406.39"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="L" class="row">
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORWGQ"
          class="seat"
          data-seat-name="64"
          cx="6023.12"
          cy="3313.43"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORWGM"
          class="seat"
          data-seat-name="63"
          cx="5966.85"
          cy="3294.78"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORWGI"
          class="seat is-available is-filtered"
          data-seat-name="62"
          cx="5910.12"
          cy="3277.75"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORWGE"
          class="seat is-available is-filtered"
          data-seat-name="61"
          cx="5852.52"
          cy="3263.68"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORWGA"
          class="seat is-available is-filtered"
          data-seat-name="60"
          cx="5794.92"
          cy="3249.62"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORVHE"
          class="seat is-available is-filtered"
          data-seat-name="59"
          cx="5737.32"
          cy="3235.55"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORVHA"
          class="seat is-available is-filtered"
          data-seat-name="58"
          cx="5679.36"
          cy="3223.26"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORVG4"
          class="seat is-available is-filtered"
          data-seat-name="57"
          cx="5620.8"
          cy="3213.84"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORVGY"
          class="seat is-available is-filtered"
          data-seat-name="56"
          cx="5562.22"
          cy="3204.43"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORVGU"
          class="seat is-available is-filtered"
          data-seat-name="55"
          cx="5503.66"
          cy="3195.01"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORVGQ"
          class="seat is-available is-filtered"
          data-seat-name="54"
          cx="5444.86"
          cy="3187.6"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORVGM"
          class="seat is-available is-filtered"
          data-seat-name="53"
          cx="5385.76"
          cy="3182.88"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORVGI"
          class="seat is-available is-filtered"
          data-seat-name="52"
          cx="5326.66"
          cy="3178.17"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORVGE"
          class="seat is-available is-filtered"
          data-seat-name="51"
          cx="5267.56"
          cy="3173.45"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORVGA"
          class="seat is-available is-filtered"
          data-seat-name="50"
          cx="5208.35"
          cy="3171"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORUHE"
          class="seat is-available is-filtered"
          data-seat-name="49"
          cx="5148.99"
          cy="3171"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORUHA"
          class="seat is-available is-filtered"
          data-seat-name="48"
          cx="5089.6"
          cy="3171"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORUG4"
          class="seat is-available is-filtered"
          data-seat-name="47"
          cx="5030.23"
          cy="3171"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORUGY"
          class="seat is-available is-filtered"
          data-seat-name="46"
          cx="4971.01"
          cy="3173.56"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORUGU"
          class="seat is-available is-filtered"
          data-seat-name="45"
          cx="4911.93"
          cy="3178.27"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORUGQ"
          class="seat is-available is-filtered"
          data-seat-name="44"
          cx="4852.78"
          cy="3182.99"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORUGM"
          class="seat is-available is-filtered"
          data-seat-name="43"
          cx="4793.68"
          cy="3187.71"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORUGI"
          class="seat"
          data-seat-name="42"
          cx="4734.91"
          cy="3195.23"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORUGE"
          class="seat"
          data-seat-name="41"
          cx="4676.38"
          cy="3204.64"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORUGA"
          class="seat"
          data-seat-name="40"
          cx="4617.86"
          cy="3214.04"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORTHE"
          class="seat"
          data-seat-name="39"
          cx="4559.35"
          cy="3223.45"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORTHA"
          class="seat is-available is-filtered"
          data-seat-name="38"
          cx="4501.43"
          cy="3235.84"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORTG4"
          class="seat"
          data-seat-name="37"
          cx="4443.86"
          cy="3249.9"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORTGY"
          class="seat"
          data-seat-name="36"
          cx="4386.3"
          cy="3263.95"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORTGU"
          class="seat"
          data-seat-name="35"
          cx="4328.75"
          cy="3278"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORTGQ"
          class="seat"
          data-seat-name="34"
          cx="4272.09"
          cy="3295.11"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5EYORTGM"
          class="seat"
          data-seat-name="33"
          cx="4215.92"
          cy="3313.72"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="M" class="row">
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORWGY"
          class="seat"
          data-seat-name="66"
          cx="6055.14"
          cy="3220.8"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORWGU"
          class="seat"
          data-seat-name="65"
          cx="5998.69"
          cy="3202.09"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORWGQ"
          class="seat"
          data-seat-name="64"
          cx="5941.89"
          cy="3184.62"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORWGM"
          class="seat"
          data-seat-name="63"
          cx="5884.1"
          cy="3170.52"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORWGI"
          class="seat"
          data-seat-name="62"
          cx="5826.32"
          cy="3156.41"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORWGE"
          class="seat"
          data-seat-name="61"
          cx="5768.54"
          cy="3142.3"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORWGA"
          class="seat is-available is-filtered"
          data-seat-name="60"
          cx="5710.58"
          cy="3129.02"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORVHE"
          class="seat is-available is-filtered"
          data-seat-name="59"
          cx="5651.85"
          cy="3119.58"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORVHA"
          class="seat is-available is-filtered"
          data-seat-name="58"
          cx="5593.12"
          cy="3110.14"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORVG4"
          class="seat is-available is-filtered"
          data-seat-name="57"
          cx="5534.42"
          cy="3100.7"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORVGY"
          class="seat is-available is-filtered"
          data-seat-name="56"
          cx="5475.63"
          cy="3091.74"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORVGU"
          class="seat is-available is-filtered"
          data-seat-name="55"
          cx="5416.34"
          cy="3087.01"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORVGQ"
          class="seat is-available is-filtered"
          data-seat-name="54"
          cx="5357.02"
          cy="3082.28"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORVGM"
          class="seat is-available is-filtered"
          data-seat-name="53"
          cx="5297.75"
          cy="3077.55"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORVGI"
          class="seat is-available is-filtered"
          data-seat-name="52"
          cx="5238.49"
          cy="3073"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORVGE"
          class="seat is-available is-filtered"
          data-seat-name="51"
          cx="5178.95"
          cy="3073"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORVGA"
          class="seat is-available is-filtered"
          data-seat-name="50"
          cx="5119.37"
          cy="3073"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORUHE"
          class="seat is-available is-filtered"
          data-seat-name="49"
          cx="5059.8"
          cy="3073"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORUHA"
          class="seat is-available is-filtered"
          data-seat-name="48"
          cx="5000.24"
          cy="3073"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORUG4"
          class="seat"
          data-seat-name="47"
          cx="4940.97"
          cy="3077.65"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORUGY"
          class="seat"
          data-seat-name="46"
          cx="4881.7"
          cy="3082.37"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORUGU"
          class="seat"
          data-seat-name="45"
          cx="4822.4"
          cy="3087.1"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORUGQ"
          class="seat"
          data-seat-name="44"
          cx="4763.11"
          cy="3091.84"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORUGM"
          class="seat"
          data-seat-name="43"
          cx="4704.33"
          cy="3100.89"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORUGI"
          class="seat"
          data-seat-name="42"
          cx="4645.58"
          cy="3110.33"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORUGE"
          class="seat"
          data-seat-name="41"
          cx="4586.85"
          cy="3119.77"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORUGA"
          class="seat"
          data-seat-name="40"
          cx="4528.15"
          cy="3129.21"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORTHE"
          class="seat"
          data-seat-name="39"
          cx="4470.21"
          cy="3142.58"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORTHA"
          class="seat"
          data-seat-name="38"
          cx="4412.43"
          cy="3156.69"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORTG4"
          class="seat"
          data-seat-name="37"
          cx="4354.67"
          cy="3170.8"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORTGY"
          class="seat"
          data-seat-name="36"
          cx="4296.88"
          cy="3184.91"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORTGU"
          class="seat"
          data-seat-name="35"
          cx="4240.12"
          cy="3202.46"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="INCU4VCFKI5E2ORTGQ"
          class="seat"
          data-seat-name="34"
          cx="4183.66"
          cy="3221.17"
          r="24.5"
        ></circle>
      </g>
    </g>
  )
}
