export default function index() {
  return (
    <g
      data-component="svg__block"
      data-section-name="RIGHT"
      data-section-id="s_28"
      class="section"
      transform=""
    >
      <g data-component="svg__row" data-row-name="A" class="row">
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUMJZ"
          class="seat"
          data-seat-name="19"
          cx="4376.5"
          cy="4404.4"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUMJY"
          class="seat"
          data-seat-name="18"
          cx="4320.42"
          cy="4428.8"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUMJX"
          class="seat"
          data-seat-name="17"
          cx="4266.23"
          cy="4457.19"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUMJW"
          class="seat"
          data-seat-name="16"
          cx="4212.05"
          cy="4485.59"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUMJV"
          class="seat"
          data-seat-name="15"
          cx="4159.43"
          cy="4516.7"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUMJU"
          class="seat"
          data-seat-name="14"
          cx="4107.74"
          cy="4549.43"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUMJT"
          class="seat is-available is-filtered"
          data-seat-name="13"
          cx="4056.44"
          cy="4582.75"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUMJS"
          class="seat"
          data-seat-name="12"
          cx="4007.61"
          cy="4619.57"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUMJR"
          class="seat"
          data-seat-name="11"
          cx="3958.76"
          cy="4656.41"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUMJQ"
          class="seat"
          data-seat-name="10"
          cx="3912.04"
          cy="4695.83"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUOI"
          class="seat"
          data-seat-name="9"
          cx="3866.34"
          cy="4736.5"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUOA"
          class="seat"
          data-seat-name="8"
          cx="3821.42"
          cy="4777.99"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUNY"
          class="seat"
          data-seat-name="7"
          cx="3779.14"
          cy="4822.2"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUNQ"
          class="seat"
          data-seat-name="6"
          cx="3736.88"
          cy="4866.39"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUNI"
          class="seat"
          data-seat-name="5"
          cx="3697.53"
          cy="4913.18"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUNA"
          class="seat"
          data-seat-name="4"
          cx="3658.92"
          cy="4960.63"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUMY"
          class="seat"
          data-seat-name="3"
          cx="3621.78"
          cy="5009.15"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUMQ"
          class="seat"
          data-seat-name="2"
          cx="3587.06"
          cy="5059.55"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJATUMI"
          class="seat"
          data-seat-name="1"
          cx="3552.29"
          cy="5110.02"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="B" class="row">
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUMRQ"
          class="seat"
          data-seat-name="20"
          cx="4344.38"
          cy="4311.57"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUMJZ"
          class="seat"
          data-seat-name="19"
          cx="4287.78"
          cy="4335.57"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUMJY"
          class="seat"
          data-seat-name="18"
          cx="4233.21"
          cy="4363.86"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUMJX"
          class="seat"
          data-seat-name="17"
          cx="4178.74"
          cy="4392.4"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUMJW"
          class="seat"
          data-seat-name="16"
          cx="4125.14"
          cy="4422.42"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUMJV"
          class="seat"
          data-seat-name="15"
          cx="4073.19"
          cy="4455.31"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUMJU"
          class="seat is-available is-filtered"
          data-seat-name="14"
          cx="4021.26"
          cy="4488.2"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUMJT"
          class="seat is-available is-filtered"
          data-seat-name="13"
          cx="3971.42"
          cy="4524.12"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUMJS"
          class="seat is-available is-filtered"
          data-seat-name="12"
          cx="3922.34"
          cy="4561.13"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUMJR"
          class="seat is-available is-filtered"
          data-seat-name="11"
          cx="3873.74"
          cy="4598.74"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUMJQ"
          class="seat is-available is-filtered"
          data-seat-name="10"
          cx="3827.82"
          cy="4639.6"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUOI"
          class="seat is-available is-filtered"
          data-seat-name="9"
          cx="3781.89"
          cy="4680.47"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUOA"
          class="seat is-available is-filtered"
          data-seat-name="8"
          cx="3737.99"
          cy="4723.43"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUNY"
          class="seat is-available is-filtered"
          data-seat-name="7"
          cx="3695.5"
          cy="4767.87"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUNQ"
          class="seat is-available is-filtered"
          data-seat-name="6"
          cx="3653.18"
          cy="4812.4"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUNI"
          class="seat"
          data-seat-name="5"
          cx="3614.39"
          cy="4860.08"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUNA"
          class="seat"
          data-seat-name="4"
          cx="3575.6"
          cy="4907.76"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUMY"
          class="seat is-available is-filtered"
          data-seat-name="3"
          cx="3538.76"
          cy="4956.91"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUMQ"
          class="seat"
          data-seat-name="2"
          cx="3503.91"
          cy="5007.51"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBDUMI"
          class="seat"
          data-seat-name="1"
          cx="3469.07"
          cy="5058.08"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="C" class="row">
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUMRS"
          class="seat"
          data-seat-name="22"
          cx="4312.27"
          cy="4218.74"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUMRR"
          class="seat"
          data-seat-name="21"
          cx="4258.12"
          cy="4241.7"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUMRQ"
          class="seat"
          data-seat-name="20"
          cx="4205.44"
          cy="4267.77"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUMJZ"
          class="seat"
          data-seat-name="19"
          cx="4153.34"
          cy="4295.07"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUMJY"
          class="seat is-available is-filtered"
          data-seat-name="18"
          cx="4101.24"
          cy="4322.37"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUMJX"
          class="seat is-available is-filtered"
          data-seat-name="17"
          cx="4051.21"
          cy="4353.24"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUMJW"
          class="seat is-available is-filtered"
          data-seat-name="16"
          cx="4001.5"
          cy="4384.71"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUMJV"
          class="seat is-available is-filtered"
          data-seat-name="15"
          cx="3951.79"
          cy="4416.19"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUMJU"
          class="seat is-available is-filtered"
          data-seat-name="14"
          cx="3904.83"
          cy="4451.59"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUMJT"
          class="seat is-available is-filtered"
          data-seat-name="13"
          cx="3857.89"
          cy="4486.99"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUMJS"
          class="seat is-available is-filtered"
          data-seat-name="12"
          cx="3811.43"
          cy="4523"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUMJR"
          class="seat is-available is-filtered"
          data-seat-name="11"
          cx="3767.51"
          cy="4562.08"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUMJQ"
          class="seat is-available is-filtered"
          data-seat-name="10"
          cx="3723.58"
          cy="4601.17"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUOI"
          class="seat is-available is-filtered"
          data-seat-name="9"
          cx="3680.78"
          cy="4641.46"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUOA"
          class="seat is-available is-filtered"
          data-seat-name="8"
          cx="3640.11"
          cy="4683.99"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUNY"
          class="seat is-available is-filtered"
          data-seat-name="7"
          cx="3599.44"
          cy="4726.52"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUNQ"
          class="seat is-available is-filtered"
          data-seat-name="6"
          cx="3560.74"
          cy="4770.74"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUNI"
          class="seat is-available is-filtered"
          data-seat-name="5"
          cx="3523.65"
          cy="4816.33"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUNA"
          class="seat is-available is-filtered"
          data-seat-name="4"
          cx="3486.51"
          cy="4861.97"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUMY"
          class="seat is-available is-filtered"
          data-seat-name="3"
          cx="3452.24"
          cy="4909.75"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUMQ"
          class="seat"
          data-seat-name="2"
          cx="3418.86"
          cy="4958.22"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJBTUMI"
          class="seat"
          data-seat-name="1"
          cx="3385.48"
          cy="5006.67"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="D" class="row">
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMRT"
          class="seat"
          data-seat-name="23"
          cx="4280.17"
          cy="4125.9"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMRS"
          class="seat"
          data-seat-name="22"
          cx="4225.67"
          cy="4149.01"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMRR"
          class="seat"
          data-seat-name="21"
          cx="4172.3"
          cy="4174.49"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMRQ"
          class="seat"
          data-seat-name="20"
          cx="4119.87"
          cy="4201.96"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMJZ"
          class="seat is-available is-filtered"
          data-seat-name="19"
          cx="4067.46"
          cy="4229.43"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMJY"
          class="seat is-available is-filtered"
          data-seat-name="18"
          cx="4016.41"
          cy="4259.28"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMJX"
          class="seat is-available is-filtered"
          data-seat-name="17"
          cx="3966.41"
          cy="4290.94"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMJW"
          class="seat is-available is-filtered"
          data-seat-name="16"
          cx="3916.41"
          cy="4322.6"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMJV"
          class="seat is-available is-filtered"
          data-seat-name="15"
          cx="3868.03"
          cy="4356.6"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMJU"
          class="seat is-available is-filtered"
          data-seat-name="14"
          cx="3820.77"
          cy="4392.24"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMJT"
          class="seat is-available is-filtered"
          data-seat-name="13"
          cx="3773.53"
          cy="4427.87"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMJS"
          class="seat is-available is-filtered"
          data-seat-name="12"
          cx="3728.22"
          cy="4465.87"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMJR"
          class="seat is-available is-filtered"
          data-seat-name="11"
          cx="3684"
          cy="4505.21"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMJQ"
          class="seat is-available is-filtered"
          data-seat-name="10"
          cx="3639.76"
          cy="4544.58"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUOI"
          class="seat is-available is-filtered"
          data-seat-name="9"
          cx="3597.84"
          cy="4586.4"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUOA"
          class="seat"
          data-seat-name="8"
          cx="3556.89"
          cy="4629.22"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUNY"
          class="seat"
          data-seat-name="7"
          cx="3515.93"
          cy="4672.05"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUNQ"
          class="seat is-available is-filtered"
          data-seat-name="6"
          cx="3477.85"
          cy="4717.34"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUNI"
          class="seat is-available is-filtered"
          data-seat-name="5"
          cx="3440.5"
          cy="4763.24"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUNA"
          class="seat is-available is-filtered"
          data-seat-name="4"
          cx="3403.17"
          cy="4809.12"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMY"
          class="seat is-available is-filtered"
          data-seat-name="3"
          cx="3369.18"
          cy="4857.58"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMQ"
          class="seat is-available is-filtered"
          data-seat-name="2"
          cx="3335.58"
          cy="4906.35"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCDUMI"
          class="seat is-available is-filtered"
          data-seat-name="1"
          cx="3302"
          cy="4955.11"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="E" class="row">
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMRU"
          class="seat"
          data-seat-name="24"
          cx="4248.05"
          cy="4033.08"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMRT"
          class="seat"
          data-seat-name="23"
          cx="4193.26"
          cy="4056.31"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMRS"
          class="seat"
          data-seat-name="22"
          cx="4139.22"
          cy="4081.19"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMRR"
          class="seat"
          data-seat-name="21"
          cx="4086.47"
          cy="4108.83"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMRQ"
          class="seat"
          data-seat-name="20"
          cx="4033.74"
          cy="4136.46"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMJZ"
          class="seat"
          data-seat-name="19"
          cx="3981.69"
          cy="4165.26"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMJY"
          class="seat"
          data-seat-name="18"
          cx="3931.4"
          cy="4197.11"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMJX"
          class="seat"
          data-seat-name="17"
          cx="3881.09"
          cy="4228.97"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMJW"
          class="seat is-available is-filtered"
          data-seat-name="16"
          cx="3831.29"
          cy="4261.57"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMJV"
          class="seat is-available is-filtered"
          data-seat-name="15"
          cx="3783.77"
          cy="4297.4"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMJU"
          class="seat is-available is-filtered"
          data-seat-name="14"
          cx="3736.24"
          cy="4333.24"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMJT"
          class="seat is-available is-filtered"
          data-seat-name="13"
          cx="3689.08"
          cy="4369.51"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMJS"
          class="seat is-available is-filtered"
          data-seat-name="12"
          cx="3644.59"
          cy="4409.1"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMJR"
          class="seat is-available is-filtered"
          data-seat-name="11"
          cx="3600.09"
          cy="4448.7"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMJQ"
          class="seat is-available is-filtered"
          data-seat-name="10"
          cx="3555.82"
          cy="4488.55"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUOI"
          class="seat is-available is-filtered"
          data-seat-name="9"
          cx="3514.65"
          cy="4531.6"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUOA"
          class="seat is-available is-filtered"
          data-seat-name="8"
          cx="3473.47"
          cy="4574.66"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUNY"
          class="seat is-available is-filtered"
          data-seat-name="7"
          cx="3432.45"
          cy="4617.86"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUNQ"
          class="seat"
          data-seat-name="6"
          cx="3394.88"
          cy="4664.04"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUNI"
          class="seat"
          data-seat-name="5"
          cx="3357.29"
          cy="4710.23"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUNA"
          class="seat"
          data-seat-name="4"
          cx="3319.83"
          cy="4756.46"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMY"
          class="seat"
          data-seat-name="3"
          cx="3286.06"
          cy="4805.49"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMQ"
          class="seat"
          data-seat-name="2"
          cx="3252.28"
          cy="4854.53"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJCTUMI"
          class="seat"
          data-seat-name="1"
          cx="3218.58"
          cy="4903.58"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="F" class="row">
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMRV"
          class="seat"
          data-seat-name="25"
          cx="4215.95"
          cy="3940.24"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMRU"
          class="seat"
          data-seat-name="24"
          cx="4160.85"
          cy="3963.61"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMRT"
          class="seat is-available is-filtered"
          data-seat-name="23"
          cx="4106.19"
          cy="3987.85"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMRS"
          class="seat"
          data-seat-name="22"
          cx="4053.18"
          cy="4015.64"
          r="24.5"
        ></circle>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMRR"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="21"
          transform="translate(3975.66, 4018.92) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMRQ"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="20"
          transform="translate(3922.65, 4046.7) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMJZ"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="19"
          transform="translate(3872.07, 4078.67) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMJY"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="18"
          transform="translate(3821.5, 4110.69) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMJX"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="17"
          transform="translate(3770.94, 4142.71) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMJW"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="16"
          transform="translate(3722.56, 4177.85) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMJV"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="15"
          transform="translate(3674.78, 4213.88) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMJU"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="14"
          transform="translate(3627.01, 4249.9) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMJT"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="13"
          transform="translate(3581.05, 4288.16) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMJS"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="12"
          transform="translate(3536.32, 4327.96) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMJR"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="11"
          transform="translate(3491.58, 4367.77) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMJQ"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="10"
          transform="translate(3448.29, 4409.07) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDDUOI"
          class="seat is-available is-filtered"
          data-seat-name="9"
          cx="3431.42"
          cy="4476.84"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDDUOA"
          class="seat"
          data-seat-name="8"
          cx="3390.05"
          cy="4520.1"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDDUNY"
          class="seat"
          data-seat-name="7"
          cx="3349.7"
          cy="4564.28"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDDUNQ"
          class="seat"
          data-seat-name="6"
          cx="3311.94"
          cy="4610.7"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDDUNI"
          class="seat"
          data-seat-name="5"
          cx="3274.16"
          cy="4657.13"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDDUNA"
          class="seat"
          data-seat-name="4"
          cx="3236.99"
          cy="4703.98"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMY"
          class="seat"
          data-seat-name="3"
          cx="3203.04"
          cy="4753.25"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMQ"
          class="seat"
          data-seat-name="2"
          cx="3169.1"
          cy="4802.52"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDDUMI"
          class="seat"
          data-seat-name="1"
          cx="3135.27"
          cy="4851.87"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="G" class="row">
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMRW"
          class="seat"
          data-seat-name="26"
          cx="4183.84"
          cy="3847.41"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMRV"
          class="seat"
          data-seat-name="25"
          cx="4128.48"
          cy="3870.88"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMRU"
          class="seat is-available is-filtered"
          data-seat-name="24"
          cx="4073.2"
          cy="3894.5"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMRT"
          class="seat is-available is-filtered"
          data-seat-name="23"
          cx="4019.94"
          cy="3922.41"
          r="24.5"
        ></circle>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMRS"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="22"
          transform="translate(3942.19, 3925.82) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMRR"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="21"
          transform="translate(3888.94, 3953.72) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMRQ"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="20"
          transform="translate(3837.42, 3984.62) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMJZ"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="19"
          transform="translate(3786.61, 4016.79) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMJY"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="18"
          transform="translate(3735.8, 4048.97) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMJX"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="17"
          transform="translate(3686.05, 4082.63) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMJW"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="16"
          transform="translate(3638.05, 4118.83) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMJV"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="15"
          transform="translate(3590.04, 4155.04) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMJU"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="14"
          transform="translate(3542.26, 4191.49) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMJT"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="13"
          transform="translate(3497.33, 4231.48) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMJS"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="12"
          transform="translate(3452.39, 4271.46) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMJR"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="11"
          transform="translate(3407.44, 4311.46) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <g
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMJQ"
          class="seat is-available is-filtered is-vip-star is-custom"
          data-seat-name="10"
          transform="translate(3365.18, 4354.19) scale(0.49)"
        >
          <circle cx="50" cy="50" r="50"></circle>
          <path
            transform="rotate(0, 50, 50)"
            d="m47.99 17.01-9 18.15-20.07 2.94-1.23 3.84 14.52 14.13-3.42 19.98 3.24 2.37L50 69l17.97 9.42 3.24-2.4-3.42-19.95 14.52-14.1-1.23-3.87-20.1-2.94-8.97-18.15h-4.02Z"
          ></path>
        </g>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDTUOI"
          class="seat is-available is-filtered"
          data-seat-name="9"
          cx="3348.14"
          cy="4422.13"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDTUOA"
          class="seat is-available is-filtered"
          data-seat-name="8"
          cx="3306.57"
          cy="4465.59"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDTUNY"
          class="seat is-available is-filtered"
          data-seat-name="7"
          cx="3266.93"
          cy="4510.73"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDTUNQ"
          class="seat is-available is-filtered"
          data-seat-name="6"
          cx="3228.97"
          cy="4557.39"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDTUNI"
          class="seat is-available is-filtered"
          data-seat-name="5"
          cx="3191.02"
          cy="4604.03"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDTUNA"
          class="seat is-available is-filtered"
          data-seat-name="4"
          cx="3154.15"
          cy="4651.48"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMY"
          class="seat is-available is-filtered"
          data-seat-name="3"
          cx="3120.05"
          cy="4700.98"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMQ"
          class="seat"
          data-seat-name="2"
          cx="3085.97"
          cy="4750.46"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJDTUMI"
          class="seat"
          data-seat-name="1"
          cx="3052.04"
          cy="4800.04"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="H" class="row">
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMRX"
          class="seat"
          data-seat-name="27"
          cx="4151.73"
          cy="3754.58"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMRW"
          class="seat"
          data-seat-name="26"
          cx="4096.12"
          cy="3778.16"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMRV"
          class="seat is-available is-filtered"
          data-seat-name="25"
          cx="4040.54"
          cy="3801.73"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMRU"
          class="seat is-available is-filtered"
          data-seat-name="24"
          cx="3986.77"
          cy="3829.15"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMRT"
          class="seat is-available is-filtered"
          data-seat-name="23"
          cx="3933.26"
          cy="3857.19"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMRS"
          class="seat is-available is-filtered"
          data-seat-name="22"
          cx="3879.79"
          cy="3885.22"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMRR"
          class="seat is-available is-filtered"
          data-seat-name="21"
          cx="3827.32"
          cy="3915.03"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMRQ"
          class="seat is-available is-filtered"
          data-seat-name="20"
          cx="3776.27"
          cy="3947.36"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMJZ"
          class="seat is-available is-filtered"
          data-seat-name="19"
          cx="3725.25"
          cy="3979.67"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMJY"
          class="seat is-available is-filtered"
          data-seat-name="18"
          cx="3674.2"
          cy="4011.99"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMJX"
          class="seat is-available is-filtered"
          data-seat-name="17"
          cx="3625.9"
          cy="4048.23"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMJW"
          class="seat is-available is-filtered"
          data-seat-name="16"
          cx="3577.69"
          cy="4084.59"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMJV"
          class="seat is-available is-filtered"
          data-seat-name="15"
          cx="3529.48"
          cy="4120.94"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMJU"
          class="seat is-available is-filtered"
          data-seat-name="14"
          cx="3482.96"
          cy="4159.38"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMJT"
          class="seat is-available is-filtered"
          data-seat-name="13"
          cx="3437.83"
          cy="4199.54"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMJS"
          class="seat is-available is-filtered"
          data-seat-name="12"
          cx="3392.7"
          cy="4239.7"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMJR"
          class="seat is-available is-filtered"
          data-seat-name="11"
          cx="3348.09"
          cy="4280.38"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMJQ"
          class="seat is-available is-filtered"
          data-seat-name="10"
          cx="3306.37"
          cy="4324.01"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUOI"
          class="seat is-available is-filtered"
          data-seat-name="9"
          cx="3264.65"
          cy="4367.63"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUOA"
          class="seat is-available is-filtered"
          data-seat-name="8"
          cx="3222.93"
          cy="4411.26"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUNY"
          class="seat is-available is-filtered"
          data-seat-name="7"
          cx="3183.99"
          cy="4457.39"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUNQ"
          class="seat is-available is-filtered"
          data-seat-name="6"
          cx="3145.88"
          cy="4504.23"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUNI"
          class="seat is-available is-filtered"
          data-seat-name="5"
          cx="3107.76"
          cy="4551.08"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUNA"
          class="seat is-available is-filtered"
          data-seat-name="4"
          cx="3071.22"
          cy="4599.12"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMY"
          class="seat is-available is-filtered"
          data-seat-name="3"
          cx="3036.95"
          cy="4648.87"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMQ"
          class="seat"
          data-seat-name="2"
          cx="3002.68"
          cy="4698.61"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJEDUMI"
          class="seat"
          data-seat-name="1"
          cx="2968.63"
          cy="4748.5"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="I" class="row">
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMRY"
          class="seat"
          data-seat-name="28"
          cx="4119.62"
          cy="3661.75"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMRX"
          class="seat"
          data-seat-name="27"
          cx="4063.81"
          cy="3685.42"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMRW"
          class="seat"
          data-seat-name="26"
          cx="4007.97"
          cy="3709.09"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMRV"
          class="seat is-available is-filtered"
          data-seat-name="25"
          cx="3953.63"
          cy="3735.88"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMRU"
          class="seat is-available is-filtered"
          data-seat-name="24"
          cx="3899.92"
          cy="3764.02"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMRT"
          class="seat"
          data-seat-name="23"
          cx="3846.23"
          cy="3792.16"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMRS"
          class="seat"
          data-seat-name="22"
          cx="3792.84"
          cy="3820.87"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMRR"
          class="seat"
          data-seat-name="21"
          cx="3741.63"
          cy="3853.3"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMRQ"
          class="seat"
          data-seat-name="20"
          cx="3690.39"
          cy="3885.74"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMJZ"
          class="seat"
          data-seat-name="19"
          cx="3639.14"
          cy="3918.2"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMJY"
          class="seat"
          data-seat-name="18"
          cx="3589.5"
          cy="3952.94"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMJX"
          class="seat"
          data-seat-name="17"
          cx="3541.09"
          cy="3989.44"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMJW"
          class="seat"
          data-seat-name="16"
          cx="3492.67"
          cy="4025.95"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMJV"
          class="seat"
          data-seat-name="15"
          cx="3444.37"
          cy="4062.54"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMJU"
          class="seat"
          data-seat-name="14"
          cx="3399.07"
          cy="4102.84"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMJT"
          class="seat"
          data-seat-name="13"
          cx="3353.78"
          cy="4143.15"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMJS"
          class="seat"
          data-seat-name="12"
          cx="3308.48"
          cy="4183.45"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMJR"
          class="seat is-available is-filtered"
          data-seat-name="11"
          cx="3264.94"
          cy="4225.54"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMJQ"
          class="seat"
          data-seat-name="10"
          cx="3223.06"
          cy="4269.33"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUOI"
          class="seat"
          data-seat-name="9"
          cx="3181.18"
          cy="4313.12"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUOA"
          class="seat"
          data-seat-name="8"
          cx="3139.36"
          cy="4356.96"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUNY"
          class="seat"
          data-seat-name="7"
          cx="3101.09"
          cy="4404"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUNQ"
          class="seat"
          data-seat-name="6"
          cx="3062.83"
          cy="4451.03"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUNI"
          class="seat"
          data-seat-name="5"
          cx="3024.55"
          cy="4498.07"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUNA"
          class="seat"
          data-seat-name="4"
          cx="2988.36"
          cy="4546.65"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMY"
          class="seat"
          data-seat-name="3"
          cx="2953.96"
          cy="4596.59"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMQ"
          class="seat"
          data-seat-name="2"
          cx="2919.56"
          cy="4646.53"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJETUMI"
          class="seat"
          data-seat-name="1"
          cx="2885.47"
          cy="4696.55"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="J" class="row">
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMZQ"
          class="seat"
          data-seat-name="30"
          cx="4087.51"
          cy="3568.91"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMRZ"
          class="seat"
          data-seat-name="29"
          cx="4033.42"
          cy="3591.86"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMRY"
          class="seat is-available is-filtered"
          data-seat-name="28"
          cx="3979.32"
          cy="3614.8"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMRX"
          class="seat is-available is-filtered"
          data-seat-name="27"
          cx="3926.13"
          cy="3639.65"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMRW"
          class="seat is-available is-filtered"
          data-seat-name="26"
          cx="3874.08"
          cy="3666.92"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMRV"
          class="seat is-available is-filtered"
          data-seat-name="25"
          cx="3822.03"
          cy="3694.2"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMRU"
          class="seat is-available is-filtered"
          data-seat-name="24"
          cx="3769.99"
          cy="3721.47"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMRT"
          class="seat is-available is-filtered"
          data-seat-name="23"
          cx="3719.43"
          cy="3751.36"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMRS"
          class="seat is-available is-filtered"
          data-seat-name="22"
          cx="3669.78"
          cy="3782.8"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMRR"
          class="seat is-available is-filtered"
          data-seat-name="21"
          cx="3620.14"
          cy="3814.23"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMRQ"
          class="seat is-available is-filtered"
          data-seat-name="20"
          cx="3570.48"
          cy="3845.68"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMJZ"
          class="seat is-available is-filtered"
          data-seat-name="19"
          cx="3523.05"
          cy="3880.31"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMJY"
          class="seat is-available is-filtered"
          data-seat-name="18"
          cx="3476.13"
          cy="3915.68"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMJX"
          class="seat is-available is-filtered"
          data-seat-name="17"
          cx="3429.24"
          cy="3951.05"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMJW"
          class="seat is-available is-filtered"
          data-seat-name="16"
          cx="3382.41"
          cy="3986.49"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMJV"
          class="seat is-available is-filtered"
          data-seat-name="15"
          cx="3338.53"
          cy="4025.54"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMJU"
          class="seat is-available is-filtered"
          data-seat-name="14"
          cx="3294.64"
          cy="4064.59"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMJT"
          class="seat"
          data-seat-name="13"
          cx="3250.75"
          cy="4103.65"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMJS"
          class="seat"
          data-seat-name="12"
          cx="3207.71"
          cy="4143.59"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMJR"
          class="seat"
          data-seat-name="11"
          cx="3167.14"
          cy="4186.02"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMJQ"
          class="seat"
          data-seat-name="10"
          cx="3126.56"
          cy="4228.45"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUOI"
          class="seat"
          data-seat-name="9"
          cx="3085.95"
          cy="4270.91"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUOA"
          class="seat"
          data-seat-name="8"
          cx="3047.18"
          cy="4314.97"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUNY"
          class="seat"
          data-seat-name="7"
          cx="3010.1"
          cy="4360.55"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUNQ"
          class="seat"
          data-seat-name="6"
          cx="2973.02"
          cy="4406.12"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUNI"
          class="seat"
          data-seat-name="5"
          cx="2935.94"
          cy="4451.7"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUNA"
          class="seat"
          data-seat-name="4"
          cx="2901.83"
          cy="4499.52"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMY"
          class="seat"
          data-seat-name="3"
          cx="2868.49"
          cy="4547.91"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMQ"
          class="seat"
          data-seat-name="2"
          cx="2835.17"
          cy="4596.29"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFDUMI"
          class="seat"
          data-seat-name="1"
          cx="2802.15"
          cy="4644.86"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="K" class="row">
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMZR"
          class="seat"
          data-seat-name="31"
          cx="4055.41"
          cy="3476.08"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMZQ"
          class="seat"
          data-seat-name="30"
          cx="4001.05"
          cy="3499.13"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMRZ"
          class="seat is-available is-filtered"
          data-seat-name="29"
          cx="3946.71"
          cy="3522.18"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMRY"
          class="seat is-available is-filtered"
          data-seat-name="28"
          cx="3892.91"
          cy="3546.42"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMRX"
          class="seat is-available is-filtered"
          data-seat-name="27"
          cx="3840.63"
          cy="3573.82"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMRW"
          class="seat"
          data-seat-name="26"
          cx="3788.32"
          cy="3601.23"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMRV"
          class="seat"
          data-seat-name="25"
          cx="3736.04"
          cy="3628.62"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMRU"
          class="seat"
          data-seat-name="24"
          cx="3684.56"
          cy="3657.44"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMRT"
          class="seat is-available is-filtered"
          data-seat-name="23"
          cx="3634.7"
          cy="3689.02"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMRS"
          class="seat is-available is-filtered"
          data-seat-name="22"
          cx="3584.81"
          cy="3720.61"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMRR"
          class="seat is-available is-filtered"
          data-seat-name="21"
          cx="3534.93"
          cy="3752.2"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMRQ"
          class="seat is-available is-filtered"
          data-seat-name="20"
          cx="3486.17"
          cy="3785.38"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMJZ"
          class="seat is-available is-filtered"
          data-seat-name="19"
          cx="3439.05"
          cy="3820.91"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMJY"
          class="seat is-available is-filtered"
          data-seat-name="18"
          cx="3391.91"
          cy="3856.46"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMJX"
          class="seat is-available is-filtered"
          data-seat-name="17"
          cx="3344.8"
          cy="3891.98"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMJW"
          class="seat is-available is-filtered"
          data-seat-name="16"
          cx="3299.21"
          cy="3929.34"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMJV"
          class="seat is-available is-filtered"
          data-seat-name="15"
          cx="3255.1"
          cy="3968.59"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMJU"
          class="seat is-available is-filtered"
          data-seat-name="14"
          cx="3211.01"
          cy="4007.83"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMJT"
          class="seat is-available is-filtered"
          data-seat-name="13"
          cx="3166.91"
          cy="4047.06"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMJS"
          class="seat is-available is-filtered"
          data-seat-name="12"
          cx="3124.89"
          cy="4088.41"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMJR"
          class="seat is-available is-filtered"
          data-seat-name="11"
          cx="3084.1"
          cy="4131.05"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMJQ"
          class="seat is-available is-filtered"
          data-seat-name="10"
          cx="3043.31"
          cy="4173.7"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUOI"
          class="seat is-available is-filtered"
          data-seat-name="9"
          cx="3002.54"
          cy="4216.33"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUOA"
          class="seat is-available is-filtered"
          data-seat-name="8"
          cx="2964.47"
          cy="4261.35"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUNY"
          class="seat is-available is-filtered"
          data-seat-name="7"
          cx="2927.23"
          cy="4307.13"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUNQ"
          class="seat is-available is-filtered"
          data-seat-name="6"
          cx="2889.98"
          cy="4352.91"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUNI"
          class="seat is-available is-filtered"
          data-seat-name="5"
          cx="2852.73"
          cy="4398.69"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUNA"
          class="seat is-available is-filtered"
          data-seat-name="4"
          cx="2818.94"
          cy="4447.1"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMY"
          class="seat is-available is-filtered"
          data-seat-name="3"
          cx="2785.46"
          cy="4495.69"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMQ"
          class="seat"
          data-seat-name="2"
          cx="2751.98"
          cy="4544.29"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJFTUMI"
          class="seat"
          data-seat-name="1"
          cx="2718.86"
          cy="4593.11"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="L" class="row">
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMZS"
          class="seat"
          data-seat-name="32"
          cx="4023.31"
          cy="3383.25"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMZR"
          class="seat"
          data-seat-name="31"
          cx="3969.42"
          cy="3406.1"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMZQ"
          class="seat"
          data-seat-name="30"
          cx="3915.52"
          cy="3428.96"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMRZ"
          class="seat"
          data-seat-name="29"
          cx="3861.75"
          cy="3452.1"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMRY"
          class="seat"
          data-seat-name="28"
          cx="3809.89"
          cy="3479.28"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMRX"
          class="seat"
          data-seat-name="27"
          cx="3758.01"
          cy="3506.47"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMRW"
          class="seat"
          data-seat-name="26"
          cx="3706.15"
          cy="3533.65"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMRV"
          class="seat"
          data-seat-name="25"
          cx="3654.28"
          cy="3560.83"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMRU"
          class="seat"
          data-seat-name="24"
          cx="3604.73"
          cy="3592"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMRT"
          class="seat"
          data-seat-name="23"
          cx="3555.28"
          cy="3623.32"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMRS"
          class="seat"
          data-seat-name="22"
          cx="3505.79"
          cy="3654.65"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMRR"
          class="seat"
          data-seat-name="21"
          cx="3456.34"
          cy="3685.97"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMRQ"
          class="seat"
          data-seat-name="20"
          cx="3409.22"
          cy="3720.66"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMJZ"
          class="seat"
          data-seat-name="19"
          cx="3362.49"
          cy="3755.9"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMJY"
          class="seat"
          data-seat-name="18"
          cx="3315.79"
          cy="3791.12"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMJX"
          class="seat"
          data-seat-name="17"
          cx="3269.09"
          cy="3826.33"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMJW"
          class="seat"
          data-seat-name="16"
          cx="3224.71"
          cy="3864.45"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMJV"
          class="seat"
          data-seat-name="15"
          cx="3180.96"
          cy="3903.39"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMJU"
          class="seat"
          data-seat-name="14"
          cx="3137.21"
          cy="3942.32"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGDUMJT"
          class="seat"
          data-seat-name="13"
          cx="3093.46"
          cy="3981.25"
          r="24.5"
        ></circle>
      </g>
      <g data-component="svg__row" data-row-name="M" class="row">
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMZT"
          class="seat"
          data-seat-name="33"
          cx="3991.21"
          cy="3290.41"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMZS"
          class="seat"
          data-seat-name="32"
          cx="3937.77"
          cy="3313.07"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMZR"
          class="seat is-available is-filtered"
          data-seat-name="31"
          cx="3884.34"
          cy="3335.73"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMZQ"
          class="seat is-available is-filtered"
          data-seat-name="30"
          cx="3830.92"
          cy="3358.39"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMRZ"
          class="seat is-available is-filtered"
          data-seat-name="29"
          cx="3779.23"
          cy="3384.71"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMRY"
          class="seat is-available is-filtered"
          data-seat-name="28"
          cx="3727.84"
          cy="3411.64"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMRX"
          class="seat is-available is-filtered"
          data-seat-name="27"
          cx="3676.44"
          cy="3438.57"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMRW"
          class="seat is-available is-filtered"
          data-seat-name="26"
          cx="3625.04"
          cy="3465.51"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMRV"
          class="seat is-available is-filtered"
          data-seat-name="25"
          cx="3575.02"
          cy="3494.82"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMRU"
          class="seat is-available is-filtered"
          data-seat-name="24"
          cx="3525.99"
          cy="3525.86"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMRT"
          class="seat is-available is-filtered"
          data-seat-name="23"
          cx="3476.96"
          cy="3556.91"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMRS"
          class="seat is-available is-filtered"
          data-seat-name="22"
          cx="3427.94"
          cy="3587.95"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMRR"
          class="seat is-available is-filtered"
          data-seat-name="21"
          cx="3379.71"
          cy="3620.17"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMRQ"
          class="seat is-available is-filtered"
          data-seat-name="20"
          cx="3333.38"
          cy="3655.11"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMJZ"
          class="seat is-available is-filtered"
          data-seat-name="19"
          cx="3287.05"
          cy="3690.05"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMJY"
          class="seat is-available is-filtered"
          data-seat-name="18"
          cx="3240.72"
          cy="3724.98"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMJX"
          class="seat is-available is-filtered"
          data-seat-name="17"
          cx="3194.54"
          cy="3760.12"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMJW"
          class="seat is-available is-filtered"
          data-seat-name="16"
          cx="3151.17"
          cy="3798.71"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMJV"
          class="seat"
          data-seat-name="15"
          cx="3107.8"
          cy="3837.3"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMJU"
          class="seat"
          data-seat-name="14"
          cx="3064.43"
          cy="3875.89"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="KJEUOSCUHJGTUMJT"
          class="seat"
          data-seat-name="13"
          cx="3021.06"
          cy="3914.49"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="JRCUMVB2JU5DSOI"
          class="seat is-available is-filtered"
          data-seat-name="99"
          cx="2551.13"
          cy="4489.6"
          r="24.5"
        ></circle>
        <circle
          data-component="svg__seat"
          id="JRCUMVB2JU5DSOA"
          class="seat is-available is-filtered"
          data-seat-name="98"
          cx="2584.46"
          cy="4440.28"
          r="24.5"
        ></circle>
      </g>
    </g>
  )
}
